title:
owner: epluno
email: customersupport@epluno.com
description: >
  Once upon a time is just a myth do not let time slip away.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://elevar.poweredbyepluno.com' # the base hostname & protocol for your site, e.g. http://example.com

# SEO
#image: /assets/images/open_graph_image.png
gaCode: # UA-XXXXXXXX-X X

# Build settings
markdown: kramdown
incremental: false
# plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
